### PR TITLE
Feat(k ui879)  upgrade to kth style v8.0.54

### PR DESCRIPTION
**Pull request by mthege**
I have: 

- upgrade to KTH style v8.0.54
- updated snapshot test

### CODE REVIEW

**Review by lenaar — CHANGES_REQUESTED** [review]
There are smth wrong with package-lock.json. Could you run `npm instal`l again and push new package-lock.json?

**Comment by mthege** [comment]
Did npm install, but also I made some kind of mistake when commit, I hope it looks alright now!

**Comment by lenaar** [comment]
It has code changes from old commits

**Review by lenaar — COMMENTED** [review]
Will not be mergeb because of some bug with commits

**Pull request closed without merging**
